#!/bin/bash

# Primero la cabecera del protocolo HTTP
# En nuestro caso no tenemos que enviar nada en dicha cabecera

# Una línea en blanco debe separar la cabecera del contenido
echo

# Contenido HTML a devolver al cliente
cat << _EOF_
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>printenv</title>
</head>
<body>
  <p>Observa las variables de entorno para este script. ¿A que algunas, como
      REMOTE_ADDRESS, REMOTE_HOST, SERVER_PORT o SCRIPT_NAME, no aparecen
      cuando ejecutas <code>printenv</code> directamente en la bash?
  </p>
  <p>Eso es porque las crea y exporta el servidor web para comunicarle
      información importante al script.
  </p>
  <pre>
$(printenv)
  </pre>
</body>
</html>
_EOF_